rm -f  *.pyc
rm -f  casapy*.log
rm -f  ipython*.log
rm -f  pointing*.txt
rm -f  pointing*.png
rm -f  oskar*.log
rm -rf *.ms
rm -rf *.vis
rm -f  *.fits
rm -rf IMG*
rm -f  *.last
#rm -rf data
#rm -f *.png
